packages:
  - "packages/chains"
  - "packages/core"
  - "packages/create-starknet"
  - "packages/typescript-config"
  - "packages/vue"
  - "examples/*"
  - "docs"
  - "!packages/create-starknet/src/**"
