packages:
  - "packages/typescript-config"
  - "packages/chains"
  - "packages/explorers"
  - "packages/providers"
  - "packages/query"
  - "packages/react"
  - "packages/vue"
  # - "packages/create-starknet"
  - "docs"
  # - "!packages/create-starknet/src/**"
